### ISSUE TITLE
resourcepacks/shaderpacks cannot be updated within an instance.

### ISSUE THREAD

**Issue by Shihyeon** [modrinth/code#1057]
### Describe the bug

The mod loader filter is applied to the resourcepack/shaderpack search, preventing updates from being recognized.

### System information

OS: Windows 11 23H2
App: v0.6.3

### Additional context

![image](https://github.com/modrinth/theseus/assets/76618619/4e2194bd-855d-47c6-8aeb-e16283ed503d)

![image](https://github.com/modrinth/theseus/assets/76618619/49263cd2-0a2c-4214-8852-f8b082a1840b)

![image](https://github.com/modrinth/theseus/assets/76618619/825b5f61-5ad9-4552-880c-93566ababfa0)

**Comment by Valaron-Jakob** [comment]
Having the same problem on newest version, preventing users from seeing shader and texturepack updates

OS: Windows 11 23H2
App: v0.7.1

### Steps to reproduce
1. Download a modpack containing an older version of a shader / texturepack
2. Select the shader / texturepack in the modpacks content-list
3. Go to `Versions`

- Loader type is filled by default, not showing updates
- Removing loader type shows versions correctly

### Expected behavior
- Loader type is not prefilled by default for shaders and texturepacks
