### ISSUE TITLE
Flatpak Modrinth App has two title bars

### ISSUE THREAD

**Issue by MaledictYtb** [modrinth/code#1153]
### Describe the bug

When installing Modrinth on Linux from Flathub, the app has two titlebars, and the two are working fine. 

![image](https://github.com/modrinth/theseus/assets/94766634/466fe252-f28e-4784-a526-d4adb29d85e8)

### System information

Fedora Kinoite 40
Latest flatpak modrinth version

**Comment by brawaru** [comment]
Unfortunately, we the Flatpak distribution is community effort and is not managed by Modrinth. Can you please verify that this is a problem with our [official distributions](https://modrinth.com/app) and not Flatpak-specific?

**Comment by MaledictYtb** [comment]
It isn't a problem on the appimage version. Should I report this bug to the flathub repo instead ?

**Comment by getchoo** [comment]
the native decorations toggle in settings should fix this

**Comment by MaledictYtb** [comment]
Is it possible to enable it by default ? Users should not have to enable this in the settings. 
Also the app has no icons.

**Comment by Kalitsune** [comment]
Well the thing is that this is an issue with the flatpak repackaging and not the modrinth launcher. The appimage version works just fine, you should create an issue on the flathub repo: https://github.com/flathub/com.modrinth.ModrinthApp

Also if the issue is coming from the repackaging and not the app it is best to avoid reporting the issue to the original app as there's not much they can do about it..
