### ISSUE TITLE
Set the modrith app for macOS category to "Game" to enable GameMode

### ISSUE THREAD

**Issue by ilgrandeanonimo** [modrinth/code#1175]
### Is your suggested enhancement related to a problem? Please describe.
During WWDC23, Apple, with macOS Sonoma, introduced GameMode which focuses resources on gaming and improves performance. This feature is automatically enabled by the system when an app with the "Game" category enters full screen.

**Some references from Apple's Website:**
https://support.apple.com/en-en/105118
https://forums.developer.apple.com/forums/thread/739387

**Comment by DrAhoss** [comment]
I second this, just downloaded the Modrinth App after swallowing my doubts and am blown away by it. It basically does it all and better. Only downside: performance is inferior to the microsoft launcher, because macos doesn't go into game mode. This is a deal breaker.

I am not sure about the complexity of adding this, but if it is just a matter  of changing the LSApplicationCategoryType it doesn't sound too hard to do.

**Comment by ilgrandeanonimo** [comment]
Tomorrow I'll create a Pull Request to add this "Enhancement"

**Comment by PainOchoco** [comment]
Hello,

I've built the app on the latest commit but unfortunately the Game Mode is not enabled on Minecraft instances created by the Modrinth Launcher.

Otherwise, it is enabled when the Modrinth Launcher is in full screen, but it's not affecting the Minecraft instances, just the launcher. So it seems like MacOS doesn't recognize Minecraft processes created by the launcher to be apps of "game" type.

MacOS version: Sonoma 14.3
Modrinth App version: [f328eec](https://github.com/modrinth/code/commit/f328eec26d4fbc9abce028e33a2ea89207d49acc)
Built with `pnpm i` and `pnpm app:build`

**Comment by PainOchoco** [comment]
For users that would like to force the Game Mode, someone found a way over on PrismLauncher repo: https://github.com/PrismLauncher/PrismLauncher/issues/1644#issuecomment-2119383766
It works! From my experience, I get +30 FPS and way less little freezes.

![image](https://github.com/user-attachments/assets/07725949-3982-4c85-a5bc-9a3cbefeea75)

So it seems that Apple has a whitelist of bundle IDs for putting child processes into Game Mode?

But it's an hacky solution and I don't think this would fit for production code and might be illegal to sign your app as another app's bundle ID...

**Comment by 1ofx9** [comment]
> For users that would like to force the Game Mode, someone found a way over on PrismLauncher repo: [PrismLauncher/PrismLauncher#1644 (comment)](https://github.com/PrismLauncher/PrismLauncher/issues/1644#issuecomment-2119383766) It works! From my experience, I get +30 FPS and way less little freezes.
> 
> ![image](https://github.com/user-attachments/assets/07725949-3982-4c85-a5bc-9a3cbefeea75)
> 
> So it seems that Apple has a whitelist of bundle IDs for putting child processes into Game Mode?
> 
> But it's an hacky solution and I don't think this would fit for production code and might be illegal to sign your app as another app's bundle ID...

how can i do this if im using modrinth?
