### ISSUE TITLE
The redesign's header is meh

### ISSUE THREAD

**Issue by doonv** [modrinth/code#2206]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate feature requests
- [X] I have checked that this feature request is not on our [roadmap](https://roadmap.modrinth.com)

### What parts of Modrinth is your feature request related too?

Website

### Is your suggested feature related to a problem? Please describe.

The new header doubles the amount of clicks required to navigate the site because you need to click on the "Browse" button before you can actually select where you want to go. This makes the experience worse for everyone.

### Describe the solution you'd like

Always show all the browsing options, like the old design did.
![image](https://github.com/user-attachments/assets/e38fa818-539a-47de-a1af-df4d460c7e69)

If screen space is an issue, make the Browse button only appear if there isn't enough space for all the options.

For the new "Get Modrinth App" and "Upgrade to Modrinth+" buttons, remove them from the header and put them somewhere else. Installing applications and subscribing to subscriptions is not something you do more than once, theres no reason for them to take so much screen space.

**Comment by Khazoda** [comment]
This is speculation but the change may have been implemented due to accessibility concerns with screen readers,
but an appearance setting to revert to a previous header style would be great. 

Moving the Browse dropdown links to the header with the current style as an option would not be much work at all:
![image](https://github.com/user-attachments/assets/94842e8a-5fa6-43d3-b704-c6f8a77f8867)

Also once you've downloaded the Modrinth Launcher, there's no reason for the button to remain there for you as a user.

**Comment by ajaxnotmeta** [comment]
what if the sign in button also has modrinth+ promotion? like besides it or somewhere
also can we flip this part of sidebar? since it actually breaks the workflow of the previous UI by a lot
![image](https://github.com/user-attachments/assets/5b8252ca-ca6e-4625-8a92-09f3f9f78071)

**Comment by doonv** [comment]
It looks like Modrinth listened to my feedback!
![image](https://github.com/user-attachments/assets/d3058be4-2f58-41cb-b240-6dfb566619ef)
This is exactly what I wanted, that was quick. Thanks!
