### ISSUE TITLE
Modrinth App Update/Version Reverting

### ISSUE THREAD

**Issue by TheMasterKitty** [modrinth/code#2362]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.2/0.8.5

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

Whenever I open modrinth, it asks for me to update, and I have clicked yes many times and it still thinks I'm on v0.8.2
![image](https://github.com/user-attachments/assets/6fb97806-1a47-4c86-b66e-23749941a367)

### Steps to reproduce

Not exactly sure how it started, but it just asks me to update whether I click no or yes (it'll restart, not ask me and the version changes, but when I reopen the launcher it asks me again and switch back).

### Expected behavior

The version should change and it shouldn't ask me again / switch back to 0.8.2

**Comment by imheavi** [comment]
This also happens to me after updating to v0.85 on Windows 11.

**Comment by MagmaBro123** [comment]
0.8.2 and 3 have update issues. You need to uninstall the app (and remove any shortcuts to it), then reinstall.

**Comment by brawaru** [comment]
In 0.8.5 we have switched to Tauri 2, and also new installer system powered by nullsoft scriptable install system (NSIS). Unfortunately, because of that, the name of the executable has changed to `theseus_gui.exe`, and a new shortcut gets created in start menu and on desktop. You are using the old shortcut to 0.8.2 executable to open Modrinth. Follow @MagmaBro123 recommendation and uninstall Modrinth App 0.8.2 in your [Apps & Features](ms-settings:appsfeatures) (<kbd>Win</kbd>+<kbd>R</kbd> and type `ms-settings:appsfeatures`).

**Comment by Zeus-2** [comment]
This is quite annoying as it likely effects a lot of us. Ohh well, is what it is.

**Comment by Zeus-2** [comment]
It seems I had two versions installed. I have removed the old version and it seems to have fixed the issue. if it reoccurs I'll reinstall fully. 
@brawaru Thanks for the help 

![image](https://github.com/user-attachments/assets/c0d8d6ed-488e-4130-91fd-9a8e0d05c698)

**Comment by TheMasterKitty** [comment]
Resolved, an update was required.
