### ISSUE TITLE
Bring Back Loader Filtering

### ISSUE THREAD

**Issue by sylv256** [modrinth/code#2880]
### Please confirm the following.

- [x] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [x] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Firefox

### Describe the bug

The loader filtering option is gone in the mod discovery/search menu.

### Steps to reproduce

1. Search for a mod
2. Choose a mod loader to filter
3. Gone

**Comment by notdonte** [comment]
Came here to complain about this, not being able to filter Forge/Fabric/Neoforge/Quilt mods is why I switched from other services in the first place, absolutely baffling change.

**Comment by IdrisQe** [comment]
Between stuff like this, the sections being shunted to a random dropdown menu now when there's lots of space available, the removal of recent versions showing on the description page, and the completely unneccessary redesign that made it more similar to Curseforge's layout a few months ago (which I don't get especially since the new _and still incomplete_ Curseforge UI change was one of the big motivators for people to move to Modrinth) I can't help but wonder why every good website ends up deciding their UI needs constant tweaking and shifting even when it's easy to use, clear, and laid out well... Usually resulting in a more obtuse and unintuitive design by the end ... And when the site still doesn't even have feature parity with Curseforge (_cough_ Mod Dependents Page _cough_)

**Comment by Geometrically** [comment]
This is a bug, fixed
