### ISSUE TITLE
When you click on a different page like mods it's stuck on loading 

### ISSUE THREAD

**Issue by Pan-cakse** [modrinth/code#335]
### Describe the bug

So let's say your gonna install mods and your on modpacks when you click mods or other ite gets stuck on loading screen and you gotta press ctrl+r to load the page

### Steps to reproduce

1. Go to list of modpacks, mods etc
2. Click or mods resourcse packs etc
3. Its stuck

### Expected behavior

Load the page within few seconds

**Comment by bubbaboogs** [comment]
Try turning off analytics in settings, that fixed it for me and many other people.

**Comment by maxomatic458** [comment]
even with analytics disabled i am getting the same error
thats from the console:

index-d7883e7a.js:1  RangeError: Maximum call stack size exceeded
    at C.truncate (index-d7883e7a.js:33:19057)
    at index-d7883e7a.js:33:19227
    at C.each (index-d7883e7a.js:33:17001)
    at C.truncate (index-d7883e7a.js:33:19199)
    at index-d7883e7a.js:33:19227
    at C.each (index-d7883e7a.js:33:17001)
    at C.truncate (index-d7883e7a.js:33:19199)
    at index-d7883e7a.js:33:19227
    at C.each (index-d7883e7a.js:33:17001)
    at C.truncate (index-d7883e7a.js:33:19199)
    
 this line seems to be causing it: 
 **https://github.com/modrinth/theseus/blob/1f478ec9fc086e6626a9ca9dd7cb290b48000440/theseus_gui/src/pages/Browse.vue#L264**
 
 but this only happens when running the built application, running it via ``cargo run`` works fine

**Comment by thesuzerain** [comment]
Should be fixed with new update- if not, please re-open
