### ISSUE TITLE
Add NeoForged modloader

### ISSUE THREAD

**Issue by Fluffyalien1422** [modrinth/code#414]
Add the NeoForged modloader to the modloader list when creating a new instance.

**Comment by EXOgreen** [comment]
Can we have some feedback on why this enhancement to add NeoForged as a modloader is "not planned"? Is it just because they currently do not have a long term downloads page set up or is this feature actually not planned. Adding support would bring parity with the modrinth website that does have Neoforged as a category.

**Comment by thewilloftheshadow** [comment]
@EXOgreen its marked as not planned because the author of the issue (who is not part of the Modrinth team) did so when closing the issue, that's not an official decision from the Modrinth team

**Comment by Poopooracoocoo** [comment]
#653 :)
