### ISSUE TITLE
Modpacks Not Downloading

### ISSUE THREAD

**Issue by Drakonix1050** [modrinth/code#677]
### Describe the bug

When I download a modpack most of the time the mods in it just don't download. It happens on every single modpack and not just oone specific one.

**Comment by thesuzerain** [comment]
Can you post:
- Your OS
- Any errors that appear
- Whether a downloaded modpack is still missing the neded mods after it successfully downloads and then you close and reopen the app

**Comment by gorbodoh** [comment]
Same issue here, happens on Windows 10 and 11 (feedback from my players).

No errors, it's just some of the mods missing. Can see the mod in .manifest file and on modrinth website, but after all mods are downloaded it will still be missing.

Tried repackage, restart app, restart PC, all nets the same result.

**Comment by thesuzerain** [comment]
> Same issue here, happens on Windows 10 and 11 (feedback from my players).
> 
> No errors, it's just some of the mods missing. Can see the mod in .manifest file and on modrinth website, but after all mods are downloaded it will still be missing.
> 
> Tried repackage, restart app, restart PC, all nets the same result.

Hmm interesting, thanks ! Can you give me a specific example of a mod pack and what isn’t getting downloaded ? I can try to look to see where in the process it’s happening

**Comment by gorbodoh** [comment]
Hi, my modrinth page is not approved yet, so I am not able to give you my link.

Attached is the zip file of the .mrpack file I uploaded there - Amplified Nether is not downloaded no matter what.
[Innicia-2.0.0.zip](https://github.com/modrinth/theseus/files/12477875/Innicia-2.0.0.zip)

**Comment by thesuzerain** [comment]
So for Amplified Nether specifically, the mrpack has it marked as unsupported for client.
```
        {
            "path": "mods/Amplified_Nether_1.20.1_v1.2.2.jar",
            "hashes": {
                "sha1": "74f1aff01b5cfda91b099cfff3ba516635470a4e",
                "sha512": "3c63ccff2b070dd91d508cb273b75d39bb1dc4f5fa74f338e3b98885444bfff1ddfa5f00bda13440817f568b6a19e1e115472a1b676140d499a8f2d930aea0a3"
            },
            "env": {
                "client": "unsupported",
                "server": "required"
            },
            "downloads": [
                "https://cdn.modrinth.com/data/wXiGiyGX/versions/QXFvBT1u/Amplified_Nether_1.20.1_v1.2.2.jar"
            ],
            "fileSize": 90598
        },

```
So it's not going to be downloaded by the launcher onto a client. If you made the pack with the launcher we are probably going to change it so that all both client/server are marked as required for a little bit. 

Are there any other ones that seemingly don't want to download? I can look into those :)

**Comment by gorbodoh** [comment]
I see, so that's the reason why it isn't downloaded. 

It would be good if modpack owners are able to mark a modpack to include server-only mods in downloading, would be useful in a situation where some users are asked to test out the modpack in a single-player world.

Unfortunately, I don't have any other modpacks that have this situation that I know, as I am only focusing on my modpack currently. Thanks!
