### ISSUE TITLE
Auto mod loader updates, OptiFine and translations

### ISSUE THREAD

**Issue by ghost** [modrinth/code#807]
I'd like to suggest some features that I think it'd enhance even more this amazing launcher:
- [ ] **Auto mod loader updates**: Not sure if it's already a thing or not, but I don't see a button where we can update the mod loader (such as Forge, Fabric, etc.) through it like the mods have, for example. I've been wondering if my Fabric loader had any update since it had been awhile without any and, when manually looking for it, there was indeed a more up-to-date version, so that could be a good improvement so one makes sure all their mods will be working properly.
![image](https://github.com/modrinth/theseus/assets/145638954/852f8e4f-8f30-4f34-be22-af1865a0cb0b)

- [ ] **OptiFine**: Why not have a way to download this mod without having to go to their official website, downloading and placing it manually into the instance folder? Maybe Modrinth could help us spare some time with this and add it built-in into the launcher as well as the other mods we can now search for.
![image](https://github.com/modrinth/theseus/assets/145638954/5ed1fd0a-418b-4965-98c6-5be167c8e715)

- [ ] **Translations**: Since Modrinth launcher will eventually get more popular as they improve, I think it's nice to start thinking about translations. Devs could open a [Crowdin](https://crowdin.com/) page and let users contribute for the language they want and, as the releases goes, they'd be getting into the launcher slowly. I'm a native Brazilian Portuguese and would love to help this project show this language, by the way!
![image](https://github.com/modrinth/theseus/assets/145638954/bfb628f5-18b2-4fc0-881a-444f657a0a36)

**Comment by catdogmat** [comment]
Sadly, I think including OptiFine would go against their TOS, so this feature could not be added.

Source: https://www.optifine.net/copyright - "It may not be placed on any web site or otherwise distributed publicly without advance written permission. Use of this mod on any other website or as a part of any public display is strictly prohibited and a violation of copyright."

**Comment by kau19an** [comment]
Oh, that sucks... Maybe they can ask OptiFine devs for permission, but it's likely a denial anyways.

**Comment by Madis0** [comment]
Please split your issue into 3 issues, this is hard to track and may just get closed/ignored by devs.

**Comment by kau19an** [comment]
I tried to do that, but all it gives me it's a "We are unable to convert the task to an issue at this time. Please try again." error. It's why I added each as tasks, so as the devs add these features into Modrinth, I'd be checking them and crossing them off the list.

**Comment by triphora** [comment]
Suggestion 1 makes sense but there is likely to already be an open issue about it.
Suggestion 2 is impossible due to the section of their ToS pointed out previously.
Suggestion 3 is already on [our roadmap](https://roadmap.modrinth.com).

In the future, you need to be making **separate issues for separate suggestions.**

**Comment by kau19an** [comment]
Okay, my bad for the multiple suggestions. I'm still learning how to use GitHub. Thanks for pointing that out and I'm glad my suggestions are on the road. Thanks!
