### ISSUE TITLE
Latest Neoforge Unavailable

### ISSUE THREAD

**Issue by snewell92** [modrinth/code#998]
### Describe the bug

Installing the latest Technical Electrical modpack fails because Modrinth does not have the required neoforge version. See waddon1/Technical-Electrical#6 for OG bug report.

![296397258-13b3febb-b672-47c8-a830-c3ad2615ffe7](https://github.com/modrinth/theseus/assets/25957964/46b9f60b-008e-4ef4-b772-daa870fa9646)

### Steps to reproduce

1. Search modpacks for Technical Electrical
2. Install version v3.5.3
3. See error message
4. In versions install v3.5.2
5. See it succeeds

### Expected behavior

Latest neoforge is available to use for mod packs (or a mod/modpack is unable to be uploaded if it required an unavailable neoforge version?)

### System information

Windows 10, Ryzen CPU and AMD GPU system (likely irrelevant). Modrinth version v0.6.3

### Additional context

<3 you're awesome and you're doing a great job <3

**Comment by catvin82** [comment]
not to speak for the maintainers, but this is probably just because the app is one month outdated now, and will be fixed in the next update

**Comment by ejektaflex** [comment]
It seems to still be outdated. When creating a new NeoForged pack, the newest version is 20.4.164-beta, which is from Feb 19th (it's Feb 27th today). The most recent version is 20.4.187.

This is a bit unfortunate, since the 20.4.164-beta installer for NeoForge no longer works due to an IP address change, leaving no sensible fallback for users. As such, Modrinth users can't easily set up a server with a matching version.
